### ISSUE TITLE
关于模版渲染

### ISSUE THREAD

**Issue by kjkq763** [easy-swoole/template#1]
使用smarty模板渲染时,修改模板文件后,有时不会返回修改后的内容,而是修改前的内容.
多次修改模板文件后,会返回多次修改前的内容.
这个问题不知道是不是进程的缓存问题?

**Comment by kiss291323003** [comment]
是的，这是进程缓存的问题。我后续看看能不能加个reboot 解决

**Comment by kiss291323003** [comment]
https://github.com/easy-swoole/template/releases/tag/1.0.3
已经解决
